version: '2'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./data:/data/db"
      
  snip_frontend: 
    build:
      context: .
      dockerfile: Dockerfile
      target: snip_frontend
      args:
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    container_name: SnipSaavy_Frontend
    expose:
      - 3000
    ports:
      - 3000:3000

  snip_backend: 
    build:
      context: .
      dockerfile: Dockerfile
      target: snip_backend
      args:
        - MONGO_URL=${MONGO_URL}
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - ALGORITHM=${ALGORITHM}
    container_name: SnipSaavy_Backend
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - mongo
      
